name: Build RadioDroid APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build Free Debug APK
        run: ./gradlew assembleFreeDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
             name: app-debug-apk
             path: **/build/outputs/apk/**/*.apk
